name: example
description: A riverpod + GoRouter integration example, with code_gen.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.3.0+4

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^12.0.1
  hooks_riverpod: ^2.4.4
  flutter_hooks: ^0.20.3
  riverpod_annotation: ^2.2.1
  shared_preferences: ^2.1.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_animate: ^4.2.0+1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  custom_lint: ^0.5.5
  riverpod_lint: ^2.3.2
  riverpod_generator: ^2.3.5
  go_router_builder: ^2.3.4

flutter:
  uses-material-design: true
