name: value_notifier
description: Sync redirect w/ value notifier legacy example

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.0
  go_router: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
